<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// Remove default loop.
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message.
 *
 * @since 1.6
 */
function genesis_404() {

	genesis_markup(
		[
			'open'    => '<article class="entry">',
			'context' => 'entry-404',
		]
	);

	genesis_markup(
		[
			'open'    => '<h1 %s>',
			'close'   => '</h1>',
			'content' => apply_filters( 'genesis_404_entry_title', __( 'UH OH!', 'genesis' ) ),
			'context' => 'entry-title',
		]
	);

	$genesis_404_content = sprintf(
		/* translators: %s: URL for current website. */
		__( "The page you're looking for<span class='white-space'> doesn't exist.</span> <p> <a href='%s'>Click here to go back to<span class='white-space'>  the homepage</a>.</span></p>", 'genesis' ),
		esc_url( trailingslashit( home_url() ) )
    );
    
    
	$genesis_404_content = sprintf( '<p>%s</p>', $genesis_404_content );

	/**
	 * The 404 content (wrapped in paragraph tags).
	 *
	 * @since 2.2.0
	 *
	 * @param string $genesis_404_content The content.
	 */
	$genesis_404_content = apply_filters( 'genesis_404_entry_content', $genesis_404_content );

	genesis_markup(
		[
			'open'    => '<div %s>',
			'close'   => '</div>',
            'content' => $genesis_404_content,
			// 'content' => $genesis_404_content . get_search_form( 0 ),
            
			'context' => 'entry-content',
		]
    );
    
    //add orange signup form
    genesis_markup(
		[
			'open'    => '<div %s>',
			'close'   => '</div>',
			'content' => do_shortcode('[styled-eo-form classes="bg-white" title="Need New Ideas?<span class=\'white-space\'> We\'ve Got \'Em.</span>" subtext="Give us a try. You can easily<span class=\'white-space\'> unsubscribe anytime.</span>"]'),
            'context' => 'signup-form',
		]
	);

	genesis_markup(
		[
			'close'   => '</article>',
			'context' => 'entry-404',
		]
	);

}

genesis();
